### ISSUE TITLE
fully automated doesn't work

### ISSUE THREAD

**Issue by dalekreitler-bnl** [NSLS-II/lsdc#11]
When running fully automated the function makeDozorInputFile (daq_macros) throws KeyError when trying to assign:

    #detector metadata from raster request
    orgX = rasterReqObj["xbeam"]
    orgY = rasterReqObj["ybeam"]

Replacing these lines with actual beam center allows for fully automated to proceed without issue. For some reason the raster request object passed to snakeRasterNormal in daq_macros during fully automated doesn't contain "xbeam", "ybeam" keys.

What is different about raster request object passed to snakeRasterNormal in fully automated vs. manual? Where are xbeam, ybeam keys added to request object?

**Comment by JunAishima** [comment]
fixed with 00b284896752d35016742bbbc678050709a0ed8b 

also related was wavelength - 83fe5c70d70aff44d2b46801821c213f745c4a8e
