### ISSUE TITLE
Implement Galil vector to standard interface

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#136]
Make the Galil vector have a similar interface to the AMX/FMX vector_program.

#131 
#138

**Comment by RobertSchaffer1** [comment]
@JunAishima I'm looking at the vector_program in mxtools, and it doesn't look like it has a prepare() function or a kickoff() function (or a run() function, for that matter); I see a go() and a proceed(), am I looking in the right spot? Also, am I correct that you intend the ophyd object updated?

**Comment by JunAishima** [comment]
sorry about the inconsistency - I am trying to systematize the functions that are to be used a bit more and have failed while writing up the issues. what I mean to have is prepare() functions that accept all necessary parameters to configure the hardware and actually get the hardware ready - which may include calling stage().

kickoff() would actually get it started.

For the Galil, prepare() could be the first part of the current run() including speed calculations and move to the start position. kickoff() would do the actual move.

**Comment by JunAishima** [comment]
OK - looks like I messed this issue up because I assumed I would be putting in prepare() functions to set things up. Instead, all of those will be within the flyer object now.

Will close this issue as we should be able to use the VectorProgram object in nyxtools.vector as is, without modifications. We will need to split up the Galil vector run function into two parts - setting up the vector, which will be run from flyer.update_parameters(), then the actual running part, which will be be extracted from the last part of VectorProgram.run() (after the error checking)
