### ISSUE TITLE
NYX - ensure governor reaches correct position

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#146]
@RobertSchaffer1 and I found that interrupting the governor transitions can result in the governor being forced to state M, yet will report a successful status.

This can result in hardware being in a dangerous position.

Add code, either to the LSDC governor transition function itself or into the data collection side of things, to check final position. If not correct, throw an exception.

**Comment by RobertSchaffer1** [comment]
@JunAishima I'm a little bit confused as to how this is happening to be honest, the set function looks like this:

def setGovRobot(state):
  if state == "DI":
    return setGovRobotDI()
  else:
    logger.info('setGovRob%s' % state)
    setRobotGovState(state)
    altName = state.lower().capitalize()
    waitGov()
    robotGovState = (getPvDesc("robot%sActive" % altName) or getPvDesc("human%sActive" % altName))
    logger.info("robot gov state = " + str(robotGovState))
    if (robotGovState != 0):
      if state in ["SA", "DA"]:
        toggleLowMagCameraSettings(state)
      return 1
    else:
      logger.info("Governor did not reach %s" % state)
      gui_message("Governor did not reach %s." % state)
      return 0

So the LSDC does check the governor state after the move. My best guess is that when the waitGov() finished it was in the correct state, but that after that it moved enough to drop to M - annoying, but can't really be caught with this type of checking. Are we monitoring the governor state PV?

**Comment by JunAishima** [comment]
Labelled as high, as problems with the governor status will decrease reliability of LSDC in production.

**Comment by JunAishima** [comment]
this was done in pull request #173, which has been merged. closing.
