### ISSUE TITLE
NYX - prevent/speed up file counting by Pilatus AreaDetector

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#152]
new description:
AreaDetector counts all images collected in the current collection. The previous description was based on the incorrect assumption that it would count all images collected since the last reset.

The task is to speed things up at the end of a collection - either speed up the checking or disable it altogether.

below is original description:

AreaDetector counts all images collected since the last reset of the counter upon the completion of a data collection. This can take a long time when many collections have been performed.

This counter should be reset after every collection so that the number of images counted is only for the last collection.

PV is: XF:19IDC-ES{Det:Pil6M}cam1:ArrayCounter

NOTE: check whether this has already been done in LSDC, but just had not been implemented correctly in the flyer

**Comment by JunAishima** [comment]
From memory, this results in annoying waits at the end of collection before control is returned to the user, thus only labelled as "medium". Testing and feedback from Kevin will be useful to determine whether this should be increased to high.

**Comment by RobertSchaffer1** [comment]
Assuming this hasn't been done in LSDC, would you prefer it to be done there, in the flyer, or at the device level?

**Comment by JunAishima** [comment]
I don't have a strong opinion, but since image counting isn't used for the Eiger, it should be somewhere it is easy to remove when we change detectors. and as a data acquisition person, I would lean towards flyer or LSDC

**Comment by JunAishima** [comment]
we don't actually care about the counter being reset, and the counting only increments up based on the files created by the current collection.

also moving to low priority

**Comment by JunAishima** [comment]
no longer using this detector. closing.
