### ISSUE TITLE
NYX - detector Z gets stuck at 500mm

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#155]
While testing before Christmas, we noticed that the detector Z axis was often getting stuck at 500mm, which prevented progress of many data collections. This then required pressing Stop on the axis on CSS before collection would continue.

This problem needs to be fixed for normal user operation. It seems like a Controls issue.

**Comment by RobertSchaffer1** [comment]
I (temporarily) removed the backlash from this axis, it appears to now arrive at the correct location in the correct state. We'll still have to investigate the underlying reasons for this and test the functionality using the LSDC.

**Comment by JunAishima** [comment]
Users or staff would have to stop the detector Z axis movement regularly, which would not be tolerable for production.

**Comment by JunAishima** [comment]
we did have problems with the backlash returning after IOC move, but it has been working, so closing.
