### ISSUE TITLE
NYX - Attenuator addition

### ISSUE THREAD

**Issue by RobertSchaffer1** [NSLS-II/lsdc#160]
The attenuator was removed from the LSDC controls process, the IOC needs to be completed (RS) and the device needs to be reinserted into the LSDC controls process (JA and/or RS).

**Comment by JunAishima** [comment]
I have put in the label as "low" for now for LSDC control, but this probably needs to be working for the beamline to function well - there will be limits on how much exposure time can overcome lack of attenuation control.

**Comment by JunAishima** [comment]
From @RobertSchaffer1 , details about the attenuator interface in EPICS (the main PVs look exactly like the ones for FMX):

For the attenuator, there are three relevant PVs:XF:19IDD-CT{Attn:RI}Energy-SP - This is the energy of the beam in eV, with allowed range of [5000, 30000]
XF:19IDD-CT{Attn:RI}Trans-SP - This is the desired transmission
XF:19IDD-CT{Attn:RI}Cmd:Set-Cmd - This is the "go" commandAn example usage:
```
[rschaffer@xf19id2-ws1 ~]$ caput XF:19IDD-CT{Attn:RI}Energy-SP 12500
Old : XF:19IDD-CT{Attn:RI}Energy-SP  5000
New : XF:19IDD-CT{Attn:RI}Energy-SP  12500[rschaffer@xf19id2-ws1 ~]$ caput XF:19IDD-CT{Attn:RI}Trans-SP .5
Old : XF:19IDD-CT{Attn:RI}Trans-SP   0.001

New : XF:19IDD-CT{Attn:RI}Trans-SP   0.5[rschaffer@xf19id2-ws1 ~]$ caput XF:19IDD-CT{Attn:RI}Cmd:Set-Cmd.PROC 1
Old : XF:19IDD-CT{Attn:RI}Cmd:Set-Cmd.PROC 0
New : XF:19IDD-CT{Attn:RI}Cmd:Set-Cmd.PROC 1
```
If you would like, I can get the energy from another PV, but for now it
needs to be set explicitly. There is also a useful readback PV,
XF:19IDD-CT{Attn:RI}Bit-I, which is a bitmap which describes the desired
 configuration, ex.
```
[rschaffer@xf19id2-ws1 ~]$ caput XF:19IDD-CT{Attn:RI}Trans-SP 0.05
Old : XF:19IDD-CT{Attn:RI}Trans-SP   1
New : XF:19IDD-CT{Attn:RI}Trans-SP   0.05
[rschaffer@xf19id2-ws1 ~]$ caget XF:19IDD-CT{Attn:RI}Bit-I
XF:19IDD-CT{Attn:RI}Bit-I      88
```
This
 tells us that at an energy of 12.5 keV and a desired transmission of
0.05, we end up with an attenuator configuration of 88 = (01011000). If
we did a caput XF:19IDD-CT{Attn:RI}Cmd:Set-Cmd.PROC 1  after this, it would insert the 0.6 mm, 0.15 mm and 0.08 mm solenoids.

**Comment by JunAishima** [comment]
working on the beamline and code pushed. closing.
