### ISSUE TITLE
GUI crashes if vector end is defined without start being defined

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#39]
Martin has reported that when he wants to define a vector but starting with the end first, the GUI crashes.
Traceback (most recent call last):
  File "/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc/lsdcGui.py", line 4739, in setVectorEndCB
    self.vecLine = self.scene.addLine(self.centerMarker.x()+self.vectorStart["graphicsitem"].x()+self.centerMarkerCharOffsetX,self.centerMarker.y()+self.vectorStart["graphicsitem"].y()+self.centerMarkerCharOffsetY,self.centerMarker.x()+vecEndMarker.x()+self.centerMarkerCharOffsetX,self.centerMarker.y()+vecEndMarker.y()+self.centerMarkerCharOffsetY, pen)
TypeError: 'NoneType' object is not subscriptable

The following code fragment is responsible - it should probably be run every time either end is changed if both ends are defined:
https://github.com/NSLS-II/lsdc/blob/23ac30e04c882f3fc5749de2cba2341364caf608/lsdcGui.py#L4721-L4740

**Comment by JunAishima** [comment]
left in branch fix_vector_definition - refactoring of vector definition and setting up the line at the correct time is done. still need to draw the line correctly and ideally refactor the speed calculation as it is done at least 3 times

**Comment by mfuchsbnl** [comment]
Last fixes work, runs stably now!
