### ISSUE TITLE
add anneal functionality to LSDC

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#44]
It is currently available for AMX.

Martin has provided a notebook where an ophyd object has been created with similar controls as the one in LSDC.

Will examine this further and see how integration of the code from the two beamlines can be reconciled.

**Comment by JunAishima** [comment]
tests on FMX, after checking the notebook code and improving that, have gone well!

**Comment by mfuchsbnl** [comment]
Works well now. Checks for status changes to cryo blocker (CB) state, and for the "annealer in" switch.
Potential improvement could be a hardware "annealer out" switch sometime in the future.

**Comment by JunAishima** [comment]
thanks! there is definitely some other code cleanup work as well...
