### ISSUE TITLE
make EDNA characterization run on each beamline's workstation 10, not just AMX's

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#57]
FMX now has a xf17id1-ws10 available or EDNA processing.

**Comment by JunAishima** [comment]
wrappers/ednaWrap sets the site - EDNA_SITE=NSLS2_AMX.

so we actually need to allow different ones for the two beamlines here as well

**Comment by JunAishima** [comment]
problem as shown in the logs is that fabio is not imported.
20210222-092811  [ERROR]: Import error while preImporting EDPluginMXThumbnailv1_1 from /usr/local/crys-local/edna-mx3/mxPluginExec/plugins/EDPluginMXThumbnail-v1.1/plugins
20210222-092811   Traceback (most recent call last): 
20210222-092811    File "/usr/local/crys-local/edna-mx3/kernel/src/EDModule.py", line 71, in preImport
20210222-092811      self.__module = __import__(self.__name)
20210222-092811    File "/usr/local/crys-local/edna-mx3/mxPluginExec/plugins/EDPluginMXThumbnail-v1.1/plugins/EDPluginMXThumbnailv1_1.py", line 32, in <module>
20210222-092811      import fabio
20210222-092811  ImportError: No module named fabio
20210222-092811  [ERROR]: Revert fragments of imported stuff from EDPluginMXThumbnailv1_1
20210222-092811  [ERROR]: Plugin EDPluginMXThumbnailv1_1 couldn't be loaded from /usr/local/crys-local/edna-mx3/mxPluginExec/plugins/EDPluginMXThumbnail-v1.1/plugins
20210222-092811  [ERROR]: EDPluginControl.loadPlugin : Cannot load plugin EDPluginMXThumbnailv1_1
20210222-092811   Traceback (most recent call last): 
20210222-092811    File "/usr/local/crys-local/edna-mx3/kernel/src/EDAction.py", line 99, in executeKernel
20210222-092811      self.preProcess()
20210222-092811    File "/usr/local/crys-local/edna-mx3/mxv1/plugins/EDPluginControlCharacterisation-v1.3/plugins/EDPluginControlCharacterisationv1_3.py", line 182, in preProcess
20210222-092811      edPluginJpeg = self.loadPlugin(self._strPluginGenerateThumbnailName)
20210222-092811    File "/usr/local/crys-local/edna-mx3/kernel/src/EDPluginControl.py", line 182, in loadPlugin
20210222-092811      raise RuntimeError(strErrorMessage)
20210222-092811  RuntimeError: EDPluginControl.loadPlugin : Cannot load plugin EDPluginMXThumbnailv1_1
20210222-092811  Summary of plugin EDPluginControlCharacterisationv1_3:

this is in the log file /GPFS/CENTRAL/xf17id1/mfuchs/fmxoperator/20200222/mx999999-1665/FMX_A016/48/0000_FMX_01_16/EDApplicationMXv1Characterisation_20210222-092810.log

system python is used by the characterization script  /usr/local/crys-local/edna-mx3/mxv1/bin/edna-mxv1-characterisation.py

(had to set up https proxy)
easy_install fabio==0.9.0 - newer versions use f string formatting, so not compatible with python 2. No egg found exception after lots of numpy API deprecation warnings. 

Have tried down to 0.8.0 and it still doesn't seem to build an egg. Have left this to Herbert

**Comment by JunAishima** [comment]
Herbert has installed fabio, and I was able to import fabio. We will see if it works now. Herbert used apt to install python-fabio and python3-fabio. After an initial failure to use the correct EDNA SITE, I asked Wuxian to restart the server, and then it used the correct file.

**Comment by wuxianshi-fmx** [comment]
The strategy calculation at FMX is now sent to the FMX computer. The correct computer is used for both Characterization and ednaCol at FMX.
