### ISSUE TITLE
optimize length of prefixes allowed

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#59]
Wuxian and I have worked on seeing whether the length of prefixes have led to ednaCol problems on FMX.

Tests have definitely found that 40 characters was too much (especially as ednaCol adds 4 characters), but 25 works well. This also agrees with what is allowed in sanitize_spreadsheet

**Comment by wuxianshi-fmx** [comment]
Prefix of 25 characters or less works for ednaCol
